import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 * Represents a window displaying shopping history records.
 * Allows users to view their shopping history records.
 */
public class history implements ActionListener {
    JFrame hist;
    JTextArea RECORD;
    JButton back;
    String rec = "";

    /**
     * Constructor initializing the shopping history window.
     * Reads shopping records from a file and displays them in a JTextArea.
     * Provides a button to navigate back to the MENU window.
     *
     * @throws FileNotFoundException if the record file is not found.
     */
    history() throws FileNotFoundException {
        hist = new JFrame("SHOPING HISTORY");
        hist.setExtendedState(JFrame.MAXIMIZED_BOTH);
        hist.setDefaultCloseOperation(EXIT_ON_CLOSE);
        hist.setBackground(Color.black);
        hist.setLayout(null);

        // Read records from file and populate JTextArea
        File REC = new File("D:\\NUST\\Semester 2\\OOP\\Project\\src\\record.txt");
        Scanner read = new Scanner(REC);
        while (read.hasNextLine()) {
            String l = read.nextLine();
            System.out.println(l);
            rec = rec + l + "\n";
        }

        // Set up JTextArea to display shopping records
        RECORD = new JTextArea(rec);
        RECORD.setFont(new Font("Arial", Font.PLAIN, 15));
        RECORD.setSize(1365, 1060);
        RECORD.setLocation(0, 50);
        RECORD.setLineWrap(true);
        RECORD.setEditable(false);
        hist.add(RECORD);
        hist.setVisible(true);

        // Create and configure back button
        back = new JButton("←");
        back.setBounds(20, 20, 70, 30);
        back.setFont((new Font("Serif", Font.PLAIN, 40)));
        hist.add(back);
        back.addActionListener(this::actionPerformed);
        hist.setVisible(true);

    }

    /**
     * Main method to initialize the shopping history window.
     *
     * @param args Command-line arguments (not used here).
     * @throws FileNotFoundException if the record file is not found.
     */
    public static void main(String[] args) throws FileNotFoundException {
        history j = new history();
    }

    /**
     * Handles the action events, specifically the back button.
     * Closes the current history window and navigates back to the MENU window.
     *
     * @param e ActionEvent generated by user interaction.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == back) {
            MENU menu = new MENU();
            hist.dispose();
        }
    }
}
